### ISSUE TITLE
Can not import pyto_ui with iOS 13.1.1

### ISSUE THREAD

**Issue by Brun0oO** [ColdGrub1384/Pyto#81] opened 2019-09-30 11:38 UTC
Hi,

I'm using Pyto version 11 (18) with iOS 13.1.1. When I try to import pyto_ui, i got "ValueError could not convert string to float '13.1.1'". Here the traceback with the HelloWorld sample script :

```
Traceback (most recent call last):
  File "Pyto.app/Samples/User Interface/Hello World.py", line 5, in <module>
    import pyto_ui as ui
  File "Pyto.app/Lib/pyto_ui.py", line 28, in <module>
    import ui_constants
  File "Pyto.app/Lib/ui_constants.py", line 15, in <module>
    if UIDevice is not None and float(str(UIDevice.currentDevice.systemVersion)) < 13:
ValueError: could not convert string to float: '13.1.1'
```

Have I do something wrong ?

**Comment by goerz** [comment] 2019-09-30 23:24
Duplicate of #79. The temporary solution is to switch to the current app store version.

**Comment by ColdGrub1384** [comment] 2019-10-01 13:37
I just submitted an updated build on TestFlight so it should be released soon.

**Closed by ColdGrub1384** 2019-10-01 13:37 UTC
