### ISSUE TITLE
CPU 100% and cell phone fever, library optimization

### ISSUE THREAD

**Issue by goodclass** [ColdGrub1384/Pyto#44] opened 2019-05-16 01:14 UTC
Hello, brother
When I was using pyto, I found that my cell phone would get hot.
There is a thread that takes up a lot of CPU under debugging. In the def input method of the console.py file, I modify the code to return to normal, as follows
> `While _PyInputHelper_ userInput = None or threading.current Thread() in ignoredThreads:`
> > `Time. sleep (0.2)`
>>  `Continue`

I've also done code optimization for libraries like numpy, and I think it should work.
[main.m](https://github.com/goodclass/pyto_ios_script/blob/master/main.m)
[so_to_framework.py](https://github.com/goodclass/pyto_ios_script/blob/master/so_to_framework.py)
[copy_framework.png](https://github.com/goodclass/pyto_ios_script/blob/master/copy_lib%20to%20framework.png)

**Comment by ColdGrub1384** [comment] 2019-05-17 00:42
Thank you! I will check that out.

**Comment by ColdGrub1384** [comment] 2019-05-18 14:42
Putting a `sleep` in the `input` function decreased **a lot** (from 99% - 100% to 0% to 3%) the CPU usage. Thank you!

**Comment by ColdGrub1384** [comment] 2019-05-18 15:20
I committed your changes to `main.m`. It's now a lot easier to load C extensions. I just changed some things that were not working. cb2a2d8ac7d2290732e56c709892f1d505b0c0a0

**Comment by goodclass** [comment] 2019-05-18 16:37
So lib needs to be modified. I also have a so_to_framework.py file. As long as the so files are put together and the file variable mulu = numpy is modified, the framework file will be generated, the project will be imported without adding the target, and then a copy framework will be established. I have a picture file on it, which has the advantage that the name of the library will not conflict in the future.

**Comment by goodclass** [comment] 2019-05-18 16:42
I'm refining the project into a demo tomorrow and putting it in github. It's one o'clock in the morning now. I'll have a rest first. Good night.

**Comment by goodclass** [comment] 2019-05-19 03:04
[PytoDemo](https://github.com/goodclass/PytoDemo)
This is a simple demo I made, which has passed the mobile phone test.
You can refer to this concise implementation.
I haven't submitted App Store in this way, just for reference.
Copy frame mode is the same, I think it's not a big problem.

**Comment by ColdGrub1384** [comment] 2019-05-19 19:33
Thank you! I added the script, but I leaved the old directories structure, because I would have to change a lot of things in Xcode Build Phases.

**Comment by ColdGrub1384** [comment] 2019-05-22 12:32
The issue is now fixed on the App Store version.

**Closed by ColdGrub1384** 2019-05-22 12:32 UTC

**Comment by goodclass** [comment] 2019-05-22 17:19
This console mode is very good, I also want to try to make a multi-functional console, support warning and error analysis, using the Pyflakes module. And the analysis of classes, functions and variables.

**Comment by cclauss** [comment] 2019-05-22 17:25
__flake8__ is a superset of __PyFlakes__ that adds even more useful tests.
