### ISSUE TITLE
Tried to install Quandl but...

### ISSUE THREAD

**Issue by jammin0921** [ColdGrub1384/Pyto#35] opened 2019-04-18 01:05 UTC
Tried installing quandl but I think the necessary dependency packages aren’t being installed when using the built-in installer. Is there a way to install a package and the dependency packages also be installed automatically? Or am I missing something?

**Comment by ColdGrub1384** [comment] 2019-04-18 01:32
Some modules like `html5lib` installs dependencies automatically. But, not this library (and other ones) 🤔. The pip on this app isn’t the original and I didn’t wrote it, it’s from [stash](https://github.com/ywangd/stash), so I don’t know where the problem is exactly, I will try to fix it. But, you are doing nothing wrong.

**Comment by jammin0921** [comment] 2019-04-18 01:34
Thanks for the notice!

**Comment by cclauss** [comment] 2019-04-18 06:50
html5lib/html5lib-python#417 describes the workaround but that entails doing `pip3 install git+https://github.com/pytries/datrie.git` and I am not sure how to do that in Pyto.

**Comment by cclauss** [comment] 2019-04-18 14:12
That PR has landed so @jammin0921 please try the pip install again.

**Comment by ColdGrub1384** [comment] 2019-05-18 15:23
Pip dependencies work now!

**Closed by ColdGrub1384** 2019-05-18 15:23 UTC
Labels: bug, third party module
